### ISSUE TITLE
Flawed validation of a domain

### ISSUE THREAD

**Issue by rafael-direito** [ATNoG/netor#12]
https://github.com/ATNoG/netor/blob/0b73721cea3eda5d015a72f373235f76c1cdfd7b/domain/api/controller.py#L74

You are validating the information using a static OSM Instance.
Take into account that the OSM Instance's location is present in the POST payload, defined via the 'url' variable. You may access this value using `data['url']`. 

Update this validation to use the OSM instance provided by the netor client.

**Comment by DanielGomes14** [comment]
I'll fix it right away
